version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: /go/src/github.com/anfimovoleh/ms-content-manager
    steps:
      - checkout
      - run: ls -la
      - run: go build -o content-manager -v ./cmd/api/main.go
  test:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: /go/src/github.com/anfimovoleh/ms-content-manager
    steps:
      - checkout
      - run: ls -la
      - run: go test ./... -v -count=1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop